# Generated by Django 3.2.9 on 2021-12-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzdevumi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name=30),
            preserve_default=False,
        ),
    ]
