# Generated by Django 3.2.9 on 2021-12-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzdevumi', '0002_visit_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='image',
            field=models.ImageField(blank=True, upload_to='visits_images'),
        ),
    ]
